### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by solbarn79** [AndreasAdler/rainloop-plugins#3]
**Problem** in `UberspaceChangePasswordDriver.php[65]`:
Warning `strtolower() expects exactly 1 parameter, 2 given` and error `Uncaught ArgumentCountError: Too few arguments to function UberspaceChangePasswordDriver::EndsWith()`

**Solution** in `UberspaceChangePasswordDriver.php[65]`:
`- return $this->EndsWith(strtolower($domainName, ".uberspace.de")) &&`
`+ return $this->EndsWith(strtolower($domainName), ".uberspace.de") &&`

**Comment by realAndrewEagle** [comment]
Thanks for reporting. Bug is fixed now.
